apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-pods-extractor-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: kubernetes-pods-extractor-sa
  namespace: kubernetes-pods-extractor 
roleRef:
  kind: ClusterRole
  name: kubernetes-pods-extractor-reader 
  apiGroup: rbac.authorization.k8s.io