apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-pods-extractor
  namespace: kubernetes-pods-extractor
  labels:
    app: kubernetes-pods-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-pods-extractor
  template:
    metadata:
      labels:
        app: kubernetes-pods-extractor
    spec:
      containers:
      - name: kubernetes-pods-extractor
        image: shayulmer/kubernetes-pods-extractor:latest
      serviceAccountName: kubernetes-pods-extractor-sa