apiVersion: v1
kind: Service
metadata:
  annotations:
  name: kubernetes-pods-extractor-service 
  namespace: kubernetes-pods-extractor
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-pods-extractor
  type: ClusterIP